### PR TITLE
docs: fix example code snippet

### PR DESCRIPTION
**Pull request by herschel666**
👋

### CODE REVIEW

**Comment by meandmax** [comment]
Yeah the example does not work at all like this, not mine and also not yours ^^

**Comment by meandmax** [comment]
thx @herschel666 for pointing this out? How are things in good old germany :)

**Comment by meandmax** [comment]
check this one: https://github.com/atlassian/browser-interaction-time/pull/9 there was not only one error in the example snippet ... ^^

**Comment by herschel666** [comment]
> How are things in good old germany :)

Fine! But I have a cold, so I'm strolling around GitHub repos, looking for code errors in READMEs. 😆

**Pull request closed without merging**
